import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

function escapeHtml(str) {
  return String(str || '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  }[c]));
}

function formatDate(iso) {
  const d = new Date(iso);
  return d.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
}

function buildHtml({ projectName, entries, totals, filterLabel, generatedAt }) {
  const rows = entries
    .map(
      (e, idx) => `
    <tr style="background:${idx % 2 === 0 ? '#ffffff' : '#f7f8fb'};">
      <td>${formatDate(e.date)}</td>
      <td style="text-transform:capitalize;">${escapeHtml(e.type)}</td>
      <td>${escapeHtml(e.person) || '-'}</td>
      <td>${escapeHtml(e.note) || '-'}</td>
      <td style="text-align:right; color:${e.type === 'income' ? '#1a8f4c' : '#c0392b'}; font-weight:600;">
        ${e.type === 'income' ? '+' : '-'}${Number(e.amount).toFixed(2)}
      </td>
    </tr>`
    )
    .join('');

  return `
  <html>
  <head>
    <meta charset="utf-8" />
    <style>
      body { font-family: Helvetica, Arial, sans-serif; color: #1E2233; padding: 28px; }
      .header { display:flex; justify-content:space-between; align-items:flex-start;
                border-bottom: 3px solid #4C6FFF; padding-bottom: 16px; margin-bottom: 20px; }
      .company { font-size: 22px; font-weight:700; color:#4C6FFF; }
      .meta { text-align:right; font-size:12px; color:#6B7080; line-height:1.5; }
      h2.project-title { font-size: 18px; margin: 4px 0 0 0; }
      .filter-note { font-size: 11px; color:#8A8FA3; margin-bottom: 18px; }
      table { width:100%; border-collapse: collapse; font-size: 12px; }
      th { text-align:left; background:#4C6FFF; color:#fff; padding: 10px 8px; }
      td { padding: 8px; border-bottom: 1px solid #EDEEF3; }
      .summary { margin-top: 24px; width: 260px; margin-left:auto; }
      .summary-row { display:flex; justify-content:space-between; padding: 6px 0; font-size: 13px; }
      .summary-row.total { border-top: 2px solid #1E2233; font-weight:700; padding-top:10px; margin-top:6px; }
      .footer { margin-top: 48px; font-size: 10px; color:#B0B4C4; text-align:center; }
    </style>
  </head>
  <body>
    <div class="header">
      <div>
        <div class="company">Expense Tracker</div>
        <h2 class="project-title">${escapeHtml(projectName)}</h2>
      </div>
      <div class="meta">
        Statement of Account<br/>Generated: ${generatedAt}
      </div>
    </div>

    ${filterLabel ? `<div class="filter-note">Filter applied: ${escapeHtml(filterLabel)}</div>` : ''}

    <table>
      <thead>
        <tr>
          <th>Date</th><th>Type</th><th>Person / Party</th><th>Note</th>
          <th style="text-align:right;">Amount</th>
        </tr>
      </thead>
      <tbody>
        ${rows || '<tr><td colspan="5" style="text-align:center; color:#8A8FA3; padding:24px;">No entries match this filter</td></tr>'}
      </tbody>
    </table>

    <div class="summary">
      <div class="summary-row"><span>Total Income</span><span style="color:#1a8f4c;">+${totals.income.toFixed(2)}</span></div>
      <div class="summary-row"><span>Total Expense</span><span style="color:#c0392b;">-${totals.expense.toFixed(2)}</span></div>
      <div class="summary-row total"><span>Net Balance</span><span>${(totals.income - totals.expense).toFixed(2)}</span></div>
    </div>

    <div class="footer">Generated by Expense Tracker &middot; ${generatedAt}</div>
  </body>
  </html>`;
}

/**
 * Builds a formal PDF statement for a project's entries and opens the
 * native share sheet so the user can save or send it.
 *
 * @param {Object} params
 * @param {string} params.projectName
 * @param {Array}  params.entries      Entries to include (already filtered by the caller)
 * @param {string} [params.filterLabel] Human-readable description of any filter applied
 * @returns {Promise<string>} the local file uri of the generated PDF
 */
export async function exportProjectToPdf({ projectName, entries, filterLabel }) {
  const totals = entries.reduce(
    (acc, e) => {
      if (e.type === 'income') acc.income += e.amount;
      else acc.expense += e.amount;
      return acc;
    },
    { income: 0, expense: 0 }
  );

  const generatedAt = new Date().toLocaleString();
  const html = buildHtml({ projectName, entries, totals, filterLabel, generatedAt });

  const { uri } = await Print.printToFileAsync({ html });

  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: `${projectName} statement`,
      UTI: 'com.adobe.pdf',
    });
  }
  return uri;
}